package com.tasnimulhasan.common.constant

import com.tasnimulhasan.entity.AlAsmaUlHusnaEntity

object AlAsmaUlHusna {
    val alAsmaUlHusnaList = listOf(
        AlAsmaUlHusnaEntity(1, "ٱلرَّحْمَٰنُ", "Ar-Raḥmān", "The Most or Entirely Merciful"),
        AlAsmaUlHusnaEntity(2, "ٱلرَّحِيمُ", "Ar-Raḥīm", "The Especially Merciful"),
        AlAsmaUlHusnaEntity(3, "ٱلْمَلِكُ", "Al-Malik", "The King and Owner of Dominion"),
        AlAsmaUlHusnaEntity(4, "ٱلْقُدُّوسُ", "Al-Quddūs", "The Absolutely Pure and Perfect"),
        AlAsmaUlHusnaEntity(5, "ٱلسَّلَامُ", "As-Salām", "The Perfection and Giver of Peace"),
        AlAsmaUlHusnaEntity(6, "ٱلْمُؤْمِنُ", "Al-Mu’min", "The Granter of Security and Faith"),
        AlAsmaUlHusnaEntity(7, "ٱلْمُهَيْمِنُ", "Al-Muhaymin", "The Guardian, The Witness, The Overseer"),
        AlAsmaUlHusnaEntity(8, "ٱلْعَزِيزُ", "Al-‘Azīz", "The Almighty, The All-Powerful, The Invincible, The Honorable"),
        AlAsmaUlHusnaEntity(9, "ٱلْجَبَّارُ", "Al-Jabbār", "The Compeller, The Restorer"),
        AlAsmaUlHusnaEntity(10, "ٱلْمُتَكَبِّرُ", "Al-Mutakabbir", "The Supreme, The Majestic"),
        AlAsmaUlHusnaEntity(11, "ٱلْخَٰلِقُ", "Al-Khāliq", "The Creator, The Maker"),
        AlAsmaUlHusnaEntity(12, "ٱلْبَارِئُ", "Al-Bāriʾ", "The Originator, The Inventor"),
        AlAsmaUlHusnaEntity(13, "ٱلْمُصَوِّرُ", "Al-Muṣawwir", "The Fashioner, The Shaper"),
        AlAsmaUlHusnaEntity(14, "ٱلْغَفَّارُ", "Al-Ghaffār", "The Constant Forgiver, The Great Forgiver"),
        AlAsmaUlHusnaEntity(15, "ٱلْقَهَّارُ", "Al-Qahhār", "The Subduer, The Ever-Dominating"),
        AlAsmaUlHusnaEntity(16, "ٱلْوَهَّابُ", "Al-Wahhāb", "The Giver of Gifts, The Bestower"),
        AlAsmaUlHusnaEntity(17, "ٱلرَّزَّاقُ", "Ar-Razzāq", "The Ever-Providing, The Constant Provider"),
        AlAsmaUlHusnaEntity(18, "ٱلْفَتَّاحُ", "Al-Fattāḥ", "The Opener, The Judge"),
        AlAsmaUlHusnaEntity(19, "ٱلْعَلِيمُ", "Al-ʿAlīm", "The All-Knowing, The Omniscient"),
        AlAsmaUlHusnaEntity(20, "ٱلْقَابِضُ", "Al-Qābiḍ", "The Withholder, The Restrainer"),
        AlAsmaUlHusnaEntity(21, "ٱلْبَاسِطُ", "Al-Bāsiṭ", "The Extender, The Expander"),
        AlAsmaUlHusnaEntity(22, "ٱلْخَافِضُ", "Al-Khāfiḍ", "The Reducer, The Abaser"),
        AlAsmaUlHusnaEntity(23, "ٱلرَّافِعُ", "Ar-Rāfiʿ", "The Exalter, The Elevator"),
        AlAsmaUlHusnaEntity(24, "ٱلْمُعِزُّ", "Al-Muʿizz", "The Honourer, The Bestower of Honor"),
        AlAsmaUlHusnaEntity(25, "ٱلْمُذِلُّ", "Al-Mudhill", "The Dishonourer, The Humiliator"),
        AlAsmaUlHusnaEntity(26, "ٱلسَّمِيعُ", "As-Samīʿ", "The All-Hearing"),
        AlAsmaUlHusnaEntity(27, "ٱلْبَصِيرُ", "Al-Baṣīr", "The All-Seeing"),
        AlAsmaUlHusnaEntity(28, "ٱلْحَكَمُ", "Al-Ḥakam", "The Judge, The Giver of Justice"),
        AlAsmaUlHusnaEntity(29, "ٱلْعَدْلُ", "Al-‘Adl", "The Utterly Just"),
        AlAsmaUlHusnaEntity(30, "ٱللَّطِيفُ", "Al-Laṭīf", "The Most Gentle, The Subtle One"),
        AlAsmaUlHusnaEntity(31, "ٱلْخَبِيرُ", "Al-Khabīr", "The All-Aware, The All-Acquainted"),
        AlAsmaUlHusnaEntity(32, "ٱلْحَلِيمُ", "Al-Ḥalīm", "The Most Forbearing"),
        AlAsmaUlHusnaEntity(33, "ٱلْعَظِيمُ", "Al-ʿAẓīm", "The Magnificent, The Supreme"),
        AlAsmaUlHusnaEntity(34, "ٱلْغَفُورُ", "Al-Ghafūr", "The Forgiving, The Exceedingly Forgiving"),
        AlAsmaUlHusnaEntity(35, "ٱلشَّكُورُ", "Ash-Shakūr", "The Most Appreciative"),
        AlAsmaUlHusnaEntity(36, "ٱلْعَلِيُّ", "Al-ʿAlī", "The Most High, The Exalted"),
        AlAsmaUlHusnaEntity(37, "ٱلْكَبِيرُ", "Al-Kabīr", "The Greatest, The Most Grand"),
        AlAsmaUlHusnaEntity(38, "ٱلْحَفِيظُ", "Al-Ḥafīẓ", "The Preserver, The All-Heedful and All-Protecting"),
        AlAsmaUlHusnaEntity(39, "ٱلْمُقِيتُ", "Al-Muqīt", "The Sustainer, The Maintainer"),
        AlAsmaUlHusnaEntity(40, "ٱلْحَسِيبُ", "Al-Ḥasīb", "The Reckoner"),
        AlAsmaUlHusnaEntity(41, "ٱلْجَلِيلُ", "Al-Jalīl", "The Majestic"),
        AlAsmaUlHusnaEntity(42, "ٱلْكَرِيمُ", "Al-Karīm", "The Most Generous, The Most Noble"),
        AlAsmaUlHusnaEntity(43, "ٱلرَّقِيبُ", "Ar-Raqīb", "The Watchful, The All-Watchful"),
        AlAsmaUlHusnaEntity(44, "ٱلْمُجِيبُ", "Al-Mujīb", "The Responsive, The Answerer"),
        AlAsmaUlHusnaEntity(45, "ٱلْوَاسِعُ", "Al-Wāsiʿ", "The All-Encompassing, the Boundless"),
        AlAsmaUlHusnaEntity(46, "ٱلْحَكِيمُ", "Al-Ḥakīm", "The All-Wise"),
        AlAsmaUlHusnaEntity(47, "ٱلْوَدُودُ", "Al-Wadūd", "The Most Loving"),
        AlAsmaUlHusnaEntity(48, "ٱلْمَجِيدُ", "Al-Majīd", "The Glorious, The Most Honorable"),
        AlAsmaUlHusnaEntity(49, "ٱلْبَاعِثُ", "Al-Bāʿith", "The Infuser of New Life, The Resurrector"),
        AlAsmaUlHusnaEntity(50, "ٱلشَّهِيدُ", "As-Shahīd", "The All-Witnessing"),
        AlAsmaUlHusnaEntity(51, "ٱلْحَقُّ", "Al-Ḥaqq", "The Absolute Truth"),
        AlAsmaUlHusnaEntity(52, "ٱلْوَكِيلُ", "Al-Wakīl", "The Trustee, The Disposer of Affairs"),
        AlAsmaUlHusnaEntity(53, "ٱلْقَوِيُّ", "Al-Qawiyy", "The All-Strong"),
        AlAsmaUlHusnaEntity(54, "ٱلْمَتِينُ", "Al-Matīn", "The Firm, The Steadfast"),
        AlAsmaUlHusnaEntity(55, "ٱلْوَلِيُّ", "Al-Waliyy", "The Protector, The Guardian"),
        AlAsmaUlHusnaEntity(56, "ٱلْحَمِيدُ", "Al-Ḥamīd", "The Praiseworthy, The Most Praised"),
        AlAsmaUlHusnaEntity(57, "ٱلْمُحْصِي", "Al-Muḥṣī", "The All-Enumerating, The Counter"),
        AlAsmaUlHusnaEntity(58, "ٱلْمُبْدِئُ", "Al-Mubdiʾ", "The Originator, The Initiator"),
        AlAsmaUlHusnaEntity(59, "ٱلْمُعِيدُ", "Al-Muʿīd", "The Restorer, The Reinstater"),
        AlAsmaUlHusnaEntity(60, "ٱلْمُحْيِي", "Al-Muḥyī", "The Giver of Life"),
        AlAsmaUlHusnaEntity(61, "ٱلْمُمِيتُ", "Al-Mumīt", "The Creator of Death"),
        AlAsmaUlHusnaEntity(62, "ٱلْحَيُّ", "Al-Ḥayy", "The Ever-Living"),
        AlAsmaUlHusnaEntity(63, "ٱلْقَيُّومُ", "Al-Qayyūm", "The Sustainer, The Self-Subsisting"),
        AlAsmaUlHusnaEntity(64, "ٱلْوَاجِدُ", "Al-Wājid", "The Finder, The Perceiver"),
        AlAsmaUlHusnaEntity(65, "ٱلْمَاجِدُ", "Al-Mājid", "The Illustrious, The Magnificent"),
        AlAsmaUlHusnaEntity(66, "ٱلْوَاحِدُ", "Al-Wāḥid", "The One, The Indivisible"),
        AlAsmaUlHusnaEntity(67, "ٱلْأَحَدُ", "Al-Aḥad", "The Unique, The Only One"),
        AlAsmaUlHusnaEntity(68, "ٱلصَّمَدُ", "Aṣ-Ṣamad", "The Eternal, The Absolute"),
        AlAsmaUlHusnaEntity(69, "ٱلْقَادِرُ", "Al-Qādir", "The Omnipotent, The All-Able"),
        AlAsmaUlHusnaEntity(70, "ٱلْمُقْتَدِرُ", "Al-Muqtadir", "The All-Powerful, The Dominant"),
        AlAsmaUlHusnaEntity(71, "ٱلْمُقَدِّمُ", "Al-Muqaddim", "The Expediter, The Promoter"),
        AlAsmaUlHusnaEntity(72, "ٱلْمُؤَخِّرُ", "Al-Muʾakhkhir", "The Delayer, The Postponer"),
        AlAsmaUlHusnaEntity(73, "ٱلْأَوَّلُ", "Al-Awwal", "The First, The Foremost"),
        AlAsmaUlHusnaEntity(74, "ٱلْآخِرُ", "Al-Ākhir", "The Last, The Utmost"),
        AlAsmaUlHusnaEntity(75, "ٱلظَّاهِرُ", "Aẓ-Ẓāhir", "The Manifest, The All-Surpassing"),
        AlAsmaUlHusnaEntity(76, "ٱلْبَاطِنُ", "Al-Bāṭin", "The Hidden One, Knower of the Hidden"),
        AlAsmaUlHusnaEntity(77, "ٱلْوَالِي", "Al-Wālī", "The Sole Governor"),
        AlAsmaUlHusnaEntity(78, "ٱلْمُتَعَالِي", "Al-Mutaʿālī", "The Self-Exalted"),
        AlAsmaUlHusnaEntity(79, "ٱلْبَرُّ", "Al-Barr", "The Source of All Goodness"),
        AlAsmaUlHusnaEntity(80, "ٱلتَّوَابُ", "At-Tawwāb", "The Ever-Pardoning"),
        AlAsmaUlHusnaEntity(81, "ٱلْمُنْتَقِمُ", "Al-Muntaqim", "The Avenger"),
        AlAsmaUlHusnaEntity(82, "ٱلْعَفُوُّ", "Al-ʿAfūw", "The Pardoner"),
        AlAsmaUlHusnaEntity(83, "ٱلرَّءُوفُ", "Ar-Raʾūf", "The Most Kind"),
        AlAsmaUlHusnaEntity(84, "مَالِكُ ٱلْمُلْكِ", "Mālik al-Mulk", "Master of the Dominion, Owner of the Kingdom"),
        AlAsmaUlHusnaEntity(85, "ذُو ٱلْجَلَالِ وَٱلْإِكْرَامِ", "Dhū al-Jalāli wa’l-Ikrām", "Possessor of Glory and Honour"),
        AlAsmaUlHusnaEntity(86, "ٱلْمُقْسِطُ", "Al-Muqsiṭ", "The Just One"),
        AlAsmaUlHusnaEntity(87, "ٱلْجَامِعُ", "Al-Jāmiʿ", "The Gatherer, the Uniter"),
        AlAsmaUlHusnaEntity(88, "ٱلْغَنِيُّ", "Al-Ghaniyy", "The Self-Sufficient, The Wealthy"),
        AlAsmaUlHusnaEntity(89, "ٱلْمُغْنِيُّ", "Al-Mughnī", "The Enricher"),
        AlAsmaUlHusnaEntity(90, "ٱلْمَانِعُ", "Al-Māniʿ", "The Withholder"),
        AlAsmaUlHusnaEntity(91, "ٱلضَّارُّ", "Aḍ-Ḍārr", "The Distresser"),
        AlAsmaUlHusnaEntity(92, "ٱلنَّافِعُ", "An-Nāfiʿ", "The Propitious, The Benefactor"),
        AlAsmaUlHusnaEntity(93, "ٱلنُّورُ", "An-Nūr", "The Light"),
        AlAsmaUlHusnaEntity(94, "ٱلْهَادِي", "Al-Hādī", "The Guide"),
        AlAsmaUlHusnaEntity(95, "ٱلْبَدِيعُ", "Al-Badīʿ", "The Incomparable Originator"),
        AlAsmaUlHusnaEntity(96, "ٱلْبَاقِي", "Al-Bāqī", "The Ever-Lasting"),
        AlAsmaUlHusnaEntity(97, "ٱلْوَارِثُ", "Al-Wāriṯ", "The Inheritor"),
        AlAsmaUlHusnaEntity(98, "ٱلرَّشِيدُ", "Ar-Rashīd", "The Guide to the Right Path"),
        AlAsmaUlHusnaEntity(99, "ٱلصَّبُورُ", "Aṣ-Ṣabūr", "The Patient")
    )
}