package com.tasnimulhasan.common.constant

import com.tasnimulhasan.entity.dua.DuaEntity

object Dua {
    val duaList = listOf(
        DuaEntity(
            id = 1,
            duaEnglish = "O Allah, You are my Lord, none has the right to be worshipped except You. You created me and I am Your servant.",
            duaArabic = "اللَّهُمَّ أَنْتَ رَبِّي لا إلهَ إلا أنتَ، خَلَقْتَني وأنا عبدُكَ",
            duaTransliteration = "Allahumma anta rabbee la ilaha illa anta, khalaqtanee wa ana ‘abduka",
            duaReference = "Jami‘ at-Tirmidhi 3393",
            duaType = "Supplication – Morning & Evening",
        ),
        DuaEntity(
            id = 2,
            duaEnglish = "O Allah, I ask You for the good of this night/day and the good of what follows it.",
            duaArabic = "اللَّهُمَّ إنِّي أَسْأَلُكَ خَيْرَ هَذِهِ اللَّيْلَةِ/اليَوْمِ وَخَيْرَ مَا بَعْدَهُ",
            duaTransliteration = "Allahumma inni as’aluka khayra hadhihi al-laylah/alyawm wa khayra ma ba’dahu",
            duaReference = "Sahih Muslim 6908",
            duaType = "Supplication – Morning & Evening",
        ),
        DuaEntity(
            id = 3,
            duaEnglish = "Glory is to Allah and praise is to Him.",
            duaArabic = "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ",
            duaTransliteration = "Subhanallahi wa bihamdihi",
            duaReference = "Sahih Muslim 1088",
            duaType = "Supplication – Morning & Evening",
        ),
        DuaEntity(
            id = 4,
            duaEnglish = "O Allah, suffice me with what You have allowed instead of what You have forbidden, and make me independent of all others besides You.",
            duaArabic = "اللَّهُمَّ اكْفِنِي بحَلالِكَ عن حَرامِكَ، وأَغْنِنِي بفَضْلِكَ عَمَّنْ سِواكَ",
            duaTransliteration = "Allahumma ikfinee bihalalika ‘an haramika, wa aghninee bifadlika ‘amman siwaka",
            duaReference = "Jami‘ at-Tirmidhi 3563",
            duaType = "Supplication – Morning & Evening",
        ),
        DuaEntity(
            id = 5,
            duaEnglish = "O Allah, Creator of the heavens and the earth, Knower of the unseen and the seen, Lord of everything and its Owner.",
            duaArabic = "اللَّهُمَّ فاطرَ السَّمواتِ والأرضِ، عالِمَ الغيبِ والشَّهادةِ، ربَّ كلِّ شيءٍ ومَليكَهُ",
            duaTransliteration = "Allahumma fatiras-samawati wal-ard, ‘alimal-ghaybi wash-shahadah, rabbakulli shay’in wa maleekah",
            duaReference = "Jami‘ at-Tirmidhi 3392",
            duaType = "Supplication – Morning & Evening",
        ),
        DuaEntity(
            id = 6,
            duaEnglish = "O Allah, I have entered the morning calling You to witness, and calling the bearers of Your Throne, Your angels, and all Your creation to witness.",
            duaArabic = "اللَّهُمَّ إنِّي أَصْبَحْتُ أُشْهِدُكَ وأُشْهِدُ حَمَلَةَ عَرْشِكَ ومَلائِكَتَكَ وجَمِيعَ خَلْقِكَ",
            duaTransliteration = "Allahumma inni asbahtu ushhiduka wa ushhidu hamalata ‘arshika wa malaa’ikataka wa jamee’a khalqika",
            duaReference = "Jami‘ at-Tirmidhi 3501",
            duaType = "Supplication – Morning & Evening",
        ),
        DuaEntity(
            id = 7,
            duaEnglish = "I am pleased with Allah as my Lord, with Islam as my religion, and with Muhammad as my Prophet.",
            duaArabic = "رَضِيتُ بِاللَّهِ رَبًّا، وبِالإسْلَامِ دِينًا، وبِمُحَمَّدٍ نَبِيًّا",
            duaTransliteration = "Radheetu billahi rabban, wa bil-islami deenan, wa bi-Muhammadin nabiyya",
            duaReference = "Jami‘ at-Tirmidhi 3389",
            duaType = "Supplication – Morning & Evening",
        ),
        DuaEntity(
            id = 8,
            duaEnglish = "Allah is sufficient for me; none has the right to be worshipped except Him. On Him I rely, and He is the Lord of the Mighty Throne.",
            duaArabic = "حَسْبِيَ اللَّهُ لا إلهَ إلا هُوَ، علَيْهِ تَوَكَّلْتُ، وَهُوَ رَبُّ العَرْشِ العَظِيمِ",
            duaTransliteration = "Hasbiyallahu la ilaha illa huwa ‘alayhi tawakkaltu wa huwa rabbul-‘arshil-‘azheem",
            duaReference = "Surah At-Tawbah 9:129",
            duaType = "Supplication – Morning & Evening",
        ),
        DuaEntity(
            id = 9,
            duaEnglish = "In Your name, O Allah, I die and I live (i.e., I sleep and I wake).",
            duaArabic = "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
            duaTransliteration = "Bismika Allahumma amutu wa ahya",
            duaReference = "Sahih Bukhari 6326",
            duaType = "Before Sleeping",
        ),
        DuaEntity(
            id = 10,
            duaEnglish = "I seek refuge in the perfect words of Allah from the evil of what He created.",
            duaArabic = "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
            duaTransliteration = "A'udhu bikalimatillahi at-tammati min sharri ma khalaq",
            duaReference = "Jami‘ at-Tirmidhi 3437",
            duaType = "Before Sleeping",
        ),
        DuaEntity(
            id = 11,
            duaEnglish = "All praise belongs to Allah who gave us life after He caused us to die (i.e., waking after sleep) — and to Him is the return.",
            duaArabic = "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ",
            duaTransliteration = "Alhamdulillah allathee ahyana ba'da ma amatana wa ilayhi an-nushoor",
            duaReference = "Sahih Bukhari 7396",
            duaType = "Before Sleeping",
        ),
        DuaEntity(
            id = 12,
            duaEnglish = "O Allah, spare me Your punishment on the Day You resurrect Your servants.",
            duaArabic = "اللَّهُمَّ قِنِي عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ",
            duaTransliteration = "Allahumma qini 'adhabaka yawma tab'athu 'ibadaka",
            duaReference = "Sunan Ibn Majah 3877",
            duaType = "Supplication – Sleep & Waking",
        ),
        DuaEntity(
            id = 13,
            duaEnglish = "I seek refuge in Allah from the accursed Satan.",
            duaArabic = "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ",
            duaTransliteration = "A'udhu billahi minash-shaytanir-rajim",
            duaReference = "Sunan Ibn Majah 808",
            duaType = "Before Sleeping",
        ),
        DuaEntity(
            id = 14,
            duaEnglish = "O Allah, do not make this world my greatest concern.",
            duaArabic = "اللَّهُمَّ لا تَجْعَلِ الدُّنْيَا أَكْبَرَ هَمِّي",
            duaTransliteration = "Allahumma la taj'alid-dunya akbara hammi",
            duaReference = "Jami‘ at-Tirmidhi 3502",
            duaType = "Night Reflection",
        ),
        DuaEntity(
            id = 15,
            duaEnglish = "My Lord, indeed I am in need of whatever good You send down to me.",
            duaArabic = "رَبِّ إِنِّي لِمَا أَنْزَلْتَ إِلَيَّ مِنْ خَيْرٍ فَقِيرٌ",
            duaTransliteration = "Rabbi inni lima anzalta ilayya min khairin faqir",
            duaReference = "Surah An-Nur 28:24",
            duaType = "Upon Waking",
        ),
        DuaEntity(
            id = 16,
            duaEnglish = "O Allah, I have submitted my soul to You and turned my face to You.",
            duaArabic = "اللَّهُمَّ إِنِّي أَسْلَمْتُ نَفْسِي إِلَيْكَ وَوَجَّهْتُ وَجْهِي إِلَيْكَ",
            duaTransliteration = "Allahumma inni aslamtu nafsi ilayka wa wajahtu wajhi ilayka",
            duaReference = "Jami‘ at-Tirmidhi 3395",
            duaType = "Before Sleeping",
        ),
        DuaEntity(
            id = 17,
            duaEnglish = "In the name of Allah, I place my trust in Allah, and there is no might nor power except with Allah.",
            duaArabic = "بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
            duaTransliteration = "Bismillahi tawakkaltu ‘alallahi wa la hawla wa la quwwata illa billah",
            duaReference = "Jami‘ at-Tirmidhi 3426",
            duaType = "Supplication – Entering & Leaving Home",
        ),
        DuaEntity(
            id = 18,
            duaEnglish = "Peace be upon you and the mercy of Allah.",
            duaArabic = "السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللَّهِ",
            duaTransliteration = "As-salamu ‘alaykum wa rahmatullah",
            duaReference = "Jami‘ at-Tirmidhi 2689",
            duaType = "Greeting When Entering Home",
        ),
        DuaEntity(
            id = 19,
            duaEnglish = "In the name of Allah.",
            duaArabic = "بِسْمِ اللَّهِ",
            duaTransliteration = "Bismillah",
            duaReference = "Sahih Bukhari 5048",
            duaType = "Before Eating",
        ),
        DuaEntity(
            id = 20,
            duaEnglish = "In the name of Allah, in its beginning and its end.",
            duaArabic = "بِسْمِ اللَّهِ أَوَّلَهُ وَآخِرَهُ",
            duaTransliteration = "Bismillahi awwalahu wa akhirahu",
            duaReference = "Sunan of Abu Dawood 3768",
            duaType = "Before Eating (If Forgot Bismillah)",
        ),
        DuaEntity(
            id = 21,
            duaEnglish = "Praise be to Allah Who has fed me this and provided it for me without any might nor power from myself.",
            duaArabic = "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ",
            duaTransliteration = "Alhamdulillahi allathee at’amani hadha wa razaqanihi min ghayri hawlin minni wa la quwwah",
            duaReference = "Jami‘ at-Tirmidhi 3458",
            duaType = "After Eating – Gratitude",
        ),
        DuaEntity(
            id = 22,
            duaEnglish = "O Allah, feed the one who fed me and give drink to the one who gave me drink.",
            duaArabic = "اللَّهُمَّ أَطْعِمْ مَنْ أَطْعَمَنِي وَاسْقِ مَنْ سَقَانِي",
            duaTransliteration = "Allahumma at’im man at’amani wasqi man saqani",
            duaReference = "Sahih Muslim 5362",
            duaType = "Dua for Host After Eating",
        ),
        DuaEntity(
            id = 23,
            duaEnglish = "O Allah, bless our food.",
            duaArabic = "اللَّهُمَّ بَارِكْ لَنَا فِي طَعَامِنَا",
            duaTransliteration = "Allahumma barik lana fi ta’amina",
            duaReference = "Jami‘ at-Tirmidhi 3455",
            duaType = "Before Eating – Asking Blessing",
        ),
        DuaEntity(
            id = 24,
            duaEnglish = "Praise be to Allah, abundant, pure, and blessed praise.",
            duaArabic = "الْحَمْدُ لِلَّهِ كَثِيرًا طَيِّبًا مُبَارَكًا فِيهِ",
            duaTransliteration = "Alhamdulillahi kathiran tayyiban mubaarakan feehi",
            duaReference = "Sahih Bukhari 5460",
            duaType = "Supplication – Before & After Meals",
        ),
        DuaEntity(
            id = 25,
            duaEnglish = "Praise be to Allah Who has satisfied our needs and given us shelter.",
            duaArabic = "الْحَمْدُ لِلَّهِ الَّذِي كَفَانَا وَأَوْانَا",
            duaTransliteration = "Alhamdulillahi allathee kafana wa awana",
            duaReference = "Sahih Muslim 6894",
            duaType = "Supplication – Before & After Meals",
        ),
        DuaEntity(
            id = 26,
            duaEnglish = "May Allah forgive you.",
            duaArabic = "غَفَرَ اللَّهُ لَكَ",
            duaTransliteration = "Ghafarallahu lak",
            duaReference = "Jami‘ at-Tirmidhi 3504",
            duaType = "Supplication – Before & After Meals",
        ),
    )
}