package com.tasnimulhasan.common.constant

import com.tasnimulhasan.entity.sura.SuraNameEntity

object SuraNames {

    val suraList = listOf(
        SuraNameEntity(1, "الفاتحة", "Al‑Fatiha", 7, "Meccan", "The Opening"),
        SuraNameEntity(2, "البقرة", "Al‑Baqarah", 286, "Medinan", "The Cow"),
        SuraNameEntity(3, "آل عمران", "Aal‑E‑Imran", 200, "Medinan", "Family of Imran"),
        SuraNameEntity(4, "النساء", "An‑Nisa", 176, "Medinan", "The Women"),
        SuraNameEntity(5, "المائدة", "Al‑Ma'idah", 120, "Medinan", "The Table Spread"),
        SuraNameEntity(6, "الأنعام", "Al‑An'am", 165, "Meccan", "The Cattle"),
        SuraNameEntity(7, "الأعراف", "Al‑A'raf", 206, "Meccan", "The Heights"),
        SuraNameEntity(8, "الأنفال", "Al‑Anfal", 75, "Medinan", "The Spoils of War"),
        SuraNameEntity(9, "التوبة", "At‑Tawbah", 129, "Medinan", "The Repentance"),
        SuraNameEntity(10, "يونس", "Yunus", 109, "Meccan", "Jonah"),
        SuraNameEntity(11, "هود", "Hud", 123, "Meccan", "Hud"),
        SuraNameEntity(12, "يوسف", "Yusuf", 111, "Meccan", "Joseph"),
        SuraNameEntity(13, "الرعد", "Ar‑Ra'd", 43, "Medinan", "The Thunder"),
        SuraNameEntity(14, "إبراهيم", "Ibrahim", 52, "Meccan", "Abraham"),
        SuraNameEntity(15, "الحجر", "Al‑Hijr", 99, "Meccan", "The Rocky Tract"),
        SuraNameEntity(16, "النحل", "An‑Nahl", 128, "Meccan", "The Bee"),
        SuraNameEntity(17, "الإسراء", "Al‑Isra", 111, "Meccan", "The Night Journey"),
        SuraNameEntity(18, "الكهف", "Al‑Kahf", 110, "Meccan", "The Cave"),
        SuraNameEntity(19, "مريم", "Maryam", 98, "Meccan", "Mary"),
        SuraNameEntity(20, "طه", "Ta‑Ha", 135, "Meccan", "Ta‑Ha (Mystical letters)"),
        SuraNameEntity(21, "الأنبياء", "Al‑Anbiya", 112, "Meccan", "The Prophets"),
        SuraNameEntity(22, "الحج", "Al‑Hajj", 78, "Medinan", "The Pilgrimage"),
        SuraNameEntity(23, "المؤمنون", "Al‑Mu’minun", 118, "Meccan", "The Believers"),
        SuraNameEntity(24, "النور", "An‑Nur", 64, "Medinan", "The Light"),
        SuraNameEntity(25, "الفرقان", "Al‑Furqan", 77, "Meccan", "The Criterion"),
        SuraNameEntity(26, "الشعراء", "Ash‑Shu'ara", 227, "Meccan", "The Poets"),
        SuraNameEntity(27, "النمل", "An‑Naml", 93, "Meccan", "The Ant"),
        SuraNameEntity(28, "القصص", "Al‑Qasas", 88, "Meccan", "The Stories"),
        SuraNameEntity(29, "العنكبوت", "Al‑Ankabut", 69, "Meccan", "The Spider"),
        SuraNameEntity(30, "الروم", "Ar‑Rum", 60, "Meccan", "The Romans"),
        SuraNameEntity(31, "لقمان", "Luqman", 34, "Meccan", "Luqman"),
        SuraNameEntity(32, "السجدة", "As‑Sajda", 30, "Meccan", "The Prostration"),
        SuraNameEntity(33, "الأحزاب", "Al‑Ahzab", 73, "Medinan", "The Combined Forces"),
        SuraNameEntity(34, "سبإ", "Saba", 54, "Meccan", "Sheba"),
        SuraNameEntity(35, "فاطر", "Fatir", 45, "Meccan", "The Originator"),
        SuraNameEntity(36, "يس", "Ya‑Sin", 83, "Meccan", "Ya‑Sin (Mystical letters)"),
        SuraNameEntity(37, "الصافات", "As‑Saffat", 182, "Meccan", "Those Who Set The Ranks"),
        SuraNameEntity(38, "ص", "Sad", 88, "Meccan", "Sad (Mystical letter)"),
        SuraNameEntity(39, "الزمر", "Az‑Zumar", 75, "Meccan", "The Groups"),
        SuraNameEntity(40, "غافر", "Ghafir", 85, "Meccan", "The Forgiver"),
        SuraNameEntity(41, "فصلت", "Fussilat", 54, "Meccan", "Explained In Detail"),
        SuraNameEntity(42, "الشورى", "Ash‑Shura", 53, "Meccan", "The Counsel"),
        SuraNameEntity(43, "الزخرف", "Az‑Zukhruf", 89, "Meccan", "The Ornaments of Gold"),
        SuraNameEntity(44, "الدخان", "Ad‑Dukhan", 59, "Meccan", "The Smoke"),
        SuraNameEntity(45, "الجاثية", "Al‑Jathiya", 37, "Meccan", "The Crouching"),
        SuraNameEntity(46, "الأحقاف", "Al‑Ahqaf", 35, "Meccan", "The Wind-Curved Sandhills"),
        SuraNameEntity(47, "محمد", "Muhammad", 38, "Medinan", "Muhammad"),
        SuraNameEntity(48, "الفتح", "Al‑Fath", 29, "Medinan", "The Victory"),
        SuraNameEntity(49, "الحجرات", "Al‑Hujurat", 18, "Medinan", "The Chambers"),
        SuraNameEntity(50, "ق", "Qaf", 45, "Meccan", "Qaf (Mystical letter)"),
        SuraNameEntity(51, "الذاريات", "Adh‑Dhariyat", 60, "Meccan", "The Winnowing Winds"),
        SuraNameEntity(52, "الطور", "At‑Tur", 49, "Meccan", "The Mount"),
        SuraNameEntity(53, "النجم", "An‑Najm", 62, "Meccan", "The Star"),
        SuraNameEntity(54, "القمر", "Al‑Qamar", 55, "Meccan", "The Moon"),
        SuraNameEntity(55, "الرحمن", "Ar‑Rahman", 78, "Medinan", "The Beneficent"),
        SuraNameEntity(56, "الواقعة", "Al‑Waqi'a", 96, "Meccan", "The Inevitable"),
        SuraNameEntity(57, "الحديد", "Al‑Hadid", 29, "Medinan", "The Iron"),
        SuraNameEntity(58, "المجادلة", "Al‑Mujadila", 22, "Medinan", "The Pleading Woman"),
        SuraNameEntity(59, "الحشر", "Al‑Hashr", 24, "Medinan", "The Exile"),
        SuraNameEntity(60, "الممتحنة", "Al‑Mumtahina", 13, "Medinan", "She That Is to Be Examined"),
        SuraNameEntity(61, "الصف", "As‑Saff", 14, "Medinan", "The Ranks"),
        SuraNameEntity(62, "الجمعة", "Al‑Jumu'a", 11, "Medinan", "The Congregation"),
        SuraNameEntity(63, "المنافقون", "Al‑Munafiqun", 11, "Medinan", "The Hypocrites"),
        SuraNameEntity(64, "التغابن", "At‑Taghabun", 18, "Medinan", "The Loss and Gain"),
        SuraNameEntity(65, "الطلاق", "At‑Talaq", 12, "Medinan", "The Divorce"),
        SuraNameEntity(66, "التحريم", "At‑Tahrim", 12, "Medinan", "The Prohibition"),
        SuraNameEntity(67, "الملك", "Al‑Mulk", 30, "Meccan", "The Sovereignty"),
        SuraNameEntity(68, "القلم", "Al‑Qalam", 52, "Meccan", "The Pen"),
        SuraNameEntity(69, "الحقّة", "Al‑Haqqah", 52, "Meccan", "The Reality"),
        SuraNameEntity(70, "المعارج", "Al‑Ma'arij", 44, "Meccan", "The Ascending Stairways"),
        SuraNameEntity(71, "نوح", "Nuh", 28, "Meccan", "Noah"),
        SuraNameEntity(72, "الجن", "Al‑Jinn", 28, "Meccan", "The Jinn"),
        SuraNameEntity(73, "المزمل", "Al‑Muzzammil", 20, "Meccan", "The Enshrouded One"),
        SuraNameEntity(74, "المدثر", "Al‑Muddaththir", 56, "Meccan", "The Cloaked One"),
        SuraNameEntity(75, "القيامة", "Al‑Qiyamah", 40, "Meccan", "The Resurrection"),
        SuraNameEntity(76, "الإنسان", "Al‑Insan", 31, "Medinan", "The Man"),
        SuraNameEntity(77, "المرسلات", "Al‑Mursalat", 50, "Meccan", "The Emissaries"),
        SuraNameEntity(78, "النبإ", "An‑Naba", 40, "Meccan", "The Announcement"),
        SuraNameEntity(79, "النازعات", "An‑Nazi'at", 46, "Meccan", "Those Who Pull Out"),
        SuraNameEntity(80, "عبس", "Abasa", 42, "Meccan", "He Frowned"),
        SuraNameEntity(81, "التكوير", "At‑Takwir", 29, "Meccan", "The Overthrowing"),
        SuraNameEntity(82, "الانفطار", "Al‑Infitar", 19, "Meccan", "The Cleaving"),
        SuraNameEntity(83, "المطففين", "Al‑Mutaffifin", 36, "Meccan", "The Defrauding"),
        SuraNameEntity(84, "الانشقاق", "Al‑Inshiqaq", 25, "Meccan", "The Sundering"),
        SuraNameEntity(85, "البروج", "Al‑Buruj", 22, "Meccan", "The Constellations"),
        SuraNameEntity(86, "الطارق", "At‑Tariq", 17, "Meccan", "The Morning Star"),
        SuraNameEntity(87, "الأعلى", "Al‑A'la", 19, "Meccan", "The Most High"),
        SuraNameEntity(88, "الغاشية", "Al‑Ghashiyah", 26, "Meccan", "The Overwhelming"),
        SuraNameEntity(89, "الفجر", "Al‑Fajr", 30, "Meccan", "The Dawn"),
        SuraNameEntity(90, "البلد", "Al‑Balad", 20, "Meccan", "The City"),
        SuraNameEntity(91, "الشمس", "Ash‑Shams", 15, "Meccan", "The Sun"),
        SuraNameEntity(92, "الليل", "Al‑Lail", 21, "Meccan", "The Night"),
        SuraNameEntity(93, "الضحى", "Ad‑Duhaa", 11, "Meccan", "The Morning Brightness"),
        SuraNameEntity(94, "الشرح", "Ash‑Sharh", 8, "Meccan", "The Relief"),
        SuraNameEntity(95, "التين", "At‑Tin", 8, "Meccan", "The Fig"),
        SuraNameEntity(96, "العلق", "Al‑Alaq", 19, "Meccan", "The Clinging Substance"),
        SuraNameEntity(97, "القدر", "Al‑Qadr", 5, "Meccan", "The Power"),
        SuraNameEntity(98, "البينة", "Al‑Bayyina", 8, "Medinan", "The Clear Proof"),
        SuraNameEntity(99, "الزلزلة", "Az‑Zalzalah", 8, "Medinan", "The Earthquake"),
        SuraNameEntity(100, "العاديات", "Al‑Adiyat", 11, "Meccan", "The Chargers"),
        SuraNameEntity(101, "القارعة", "Al‑Qari'ah", 11, "Meccan", "The Calamity"),
        SuraNameEntity(102, "التكاثر", "At‑Takathur", 8, "Meccan", "The Rivalry in world increase"),
        SuraNameEntity(103, "العصر", "Al‑Asr", 3, "Meccan", "The Declining Day"),
        SuraNameEntity(104, "الهمزة", "Al‑Humazah", 9, "Meccan", "The Traducer"),
        SuraNameEntity(105, "الفيل", "Al‑Fil", 5, "Meccan", "The Elephant"),
        SuraNameEntity(106, "قريش", "Quraish", 4, "Meccan", "Quraysh"),
        SuraNameEntity(107, "الماعون", "Al‑Ma'un", 7, "Meccan", "Small Kindnesses"),
        SuraNameEntity(108, "الكوثر", "Al‑Kawthar", 3, "Meccan", "Abundance"),
        SuraNameEntity(109, "الكافرون", "Al‑Kafirun", 6, "Meccan", "The Disbelievers"),
        SuraNameEntity(110, "النصر", "An‑Nasr", 3, "Medinan", "The Divine Support"),
        SuraNameEntity(111, "المسد", "Al‑Masad", 5, "Meccan", "The Palm Fiber"),
        SuraNameEntity(112, "الإخلاص", "Al‑Ikhlas", 4, "Meccan", "The Sincerity"),
        SuraNameEntity(113, "الفلق", "Al‑Falaq", 5, "Meccan", "The Daybreak"),
        SuraNameEntity(114, "الناس", "An‑Nas", 6, "Meccan", "Mankind")
    )

}